- geonotebook/kernel.py
- geonotebook/layers.py
- geonotebook/static/index.js
- geonotebook/static/map.js
- geonotebook/vis/geoserver.py
- geonotebook/vis/geoserver/__init__.py
- geonotebook/vis/geoserver/geoserver.py
- geonotebook/vis/geoserver/sld.py
- geonotebook/wrappers/__init__.py
- geonotebook/wrappers/image.py
- notebooks/geoserver.ipynb
> Band selection

- geonotebook/layers.py
- geonotebook/wrappers/__init__.py
- notebooks/geoserver.ipynb
Fixes the region code which was accidentally not refactored as apart of the band selection branch
> Fixing region code

- geonotebook/kernel.py
- geonotebook/layers.py
- geonotebook/static/map.js
- geonotebook/vis/geoserver/geoserver.py
- geonotebook/wrappers/__init__.py
- geonotebook/wrappers/image.py
- notebooks/Geoserver.ipynb
- notebooks/Time Series.ipynb
- tests/test_wrappers_bands.py
@dorukozturk PTAL - There is a TIme Series.ipynb notebook that should let you test the functionality.  You just need the NBAR data converted to GeoTIFFs and to change the DATA_DIR variable in cell 3.
> Raster data collections

- geonotebook/jsonrpc.py
- geonotebook/static/index.js
- geonotebook/static/lib/jsonrpc.js
> Use a UUIDv4 rather than TESTID for all message ids

- README.md
- setup.py
This should install the kernel after setup on 'install' and 'develop'
and also copy any files in data_files  on 'develop' to external
locations.
> Setuptools refactor

- geonotebook/vis/geoserver/geoserver.py
- geonotebook/vis/geoserver/sld.py
> Set a default colormap for singleband

- geonotebook/templates/notebook.html
- setup.py
@kotfic This should have been part of the map height PR and is why you were experiencing the weird wrapping.
> Install server extension from setup.py

- .gitignore
- requirements-dev.txt
- tests/test_geoserver_sld.py
- tests/test_layers_collection.py
- tests/test_wrappers_bands.py
- tox.ini
> Convert test cases to pytest

- devops/roles/geonotebook/tasks/main.yml
- devops/site.yml
- notebooks/requirements.txt
@danlamanna @dorukozturk if one of you could launch and confirm that 01_Example and 02_Geoserver work that would be great!
> A few things that need to be added for example notebooks to work

- circle.yml
- geonotebook/kernel.py
- geonotebook/static/index.js
- geonotebook/static/lib/utils.js
- geonotebook/static/map.js
- geonotebook/vis/geoserver/geoserver.py
- requirements.txt
- tests/test_geonotebook.py
- tests/test_remote.py
Fixes https://github.com/OpenGeoscience/geonotebook/issues/45
Still need to add some tests
> Expand rpc protocol

- README.md
- setup.py
Instead, suggest how to use tox as our test runner.
> Remove remnants from running setup.py test

- circle.yml
- js/package.json
Example of the Circle CI output can be seen [here](https://circleci.com/gh/OpenGeoscience/geonotebook/150).
> Output eslint JUnit XML for Circle CI

- js/src/Geonotebook.js
- js/src/css/styles.css
> Prefix css to prevent modifying default python kerenl look/feel

- geonotebook/annotations.py
- geonotebook/kernel.py
- geonotebook/layers.py
- js/src/Geonotebook.js
- js/src/MapObject.js
- notebooks/02_Geoserver.ipynb
- notebooks/03_Time Series.ipynb
This is to address #9.
This is WIP. It doesn't redraw annotations correctly, and it ignores the zIndex of layers.
> Rudimentary object serialization

- js/package.json
- js/src/Geonotebook.js
- js/src/MapObject.js
- js/src/css/styles.css
> Add a drag control to adjust map width

- README.md
This documentation could be much better.  At least it is an improvement over the currently incorrect documentation.
> Update geonotebook repo documentation

- geonotebook/vis/ktile/ktile.py
- geonotebook/vis/ktile/provider.py
> Fix intermittent issue with gdal vrt rendering

- setup.py
@danlamanna Should fix your symlink issue.
> Add sourcemaps to package data

- geonotebook/config.py
- geonotebook/vis/geoserver/geoserver.py
- geonotebook/vis/geoserver/sld.py
- setup.py
This is designed to allow separate packages to inject custom vis servers into the Config object. This is how we will support the Spark/Geotrellis vis server. Eventually Geoserver vis server should be pulled out into its own package (and refactored/fixed).
@danlamanna @jbeezley PTAL
> Visserver entry point

- js/src/map/base.js
> Fix issue with removing layers

- Dockerfile
- devops/docker/jupyter.sh
Also add -U to requirements install so we don't end up with old
versions of unpinned packages
Install libproj-dev, now nessisary after re-projection code added to
annotations
@dorukozturk  PTAL
> Update dockerfile to use ubuntu 16.04

- notebooks/demos/FOSS4G 2017 Demo.ipynb
- notebooks/demos/JupyterCon 2017 Demo.ipynb
- notebooks/demos/README.md
This also adds a readme that links out to slides - and eventually to videos once those are posted.
> Add recent demo notebooks

- README.md
- docs/source/installation.rst
If you try and clone from git you get Permission denied errors
> Change docs to clone from https rather than git
